-- Run once in the SQL Editor of a new Supabase project.
begin;

create table public.vehicles (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  nickname text not null check (length(trim(nickname)) > 0),
  make text not null,
  model text not null,
  year integer not null check (year between 1886 and 2200),
  plate_number text not null check (length(trim(plate_number)) > 0),
  current_odometer double precision not null check (current_odometer >= 0 and current_odometer < 1e12),
  odometer_unit text not null default 'km' check (odometer_unit in ('km', 'mi')),
  notes text not null default '',
  unique (id, user_id)
);
create unique index vehicles_owner_plate on public.vehicles
  (user_id, upper(regexp_replace(plate_number, '[[:space:]-]', '', 'g')));

create table public.maintenance_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  vehicle_id bigint not null,
  maintenance_type text not null,
  service_date date not null,
  odometer double precision not null check (odometer >= 0 and odometer < 1e12),
  cost double precision not null check (cost >= 0 and cost < 1e12),
  service_provider text not null default '',
  notes text not null default '',
  foreign key (vehicle_id, user_id) references public.vehicles(id, user_id) on delete cascade
);
create index records_owner_vehicle on public.maintenance_records(user_id, vehicle_id, service_date);

create table public.maintenance_schedules (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  vehicle_id bigint not null,
  maintenance_type text not null,
  due_date date not null,
  due_odometer double precision not null check (due_odometer >= 0 and due_odometer < 1e12),
  notes text not null default '',
  reminder_enabled integer not null default 1 check (reminder_enabled in (0, 1)),
  status text not null default 'upcoming' check (status in ('upcoming', 'completed')),
  foreign key (vehicle_id, user_id) references public.vehicles(id, user_id) on delete cascade
);
create index schedules_owner_vehicle on public.maintenance_schedules(user_id, vehicle_id, due_date);

create table public.tires (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  vehicle_id bigint not null,
  position text not null check (position in ('Front left', 'Front right', 'Rear left', 'Rear right', 'Spare')),
  brand text not null default '',
  manufactured_on date not null check (manufactured_on >= date '2000-01-01' and manufactured_on <= current_date),
  replacement_years integer not null default 6 check (replacement_years between 1 and 10),
  notes text not null default '',
  foreign key (vehicle_id, user_id) references public.vehicles(id, user_id) on delete cascade,
  unique (vehicle_id, position)
);
create index tires_owner_vehicle on public.tires(user_id, vehicle_id);

create table public.settings (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  key text not null,
  value text not null,
  primary key (user_id, key)
);

alter table public.vehicles enable row level security;
alter table public.maintenance_records enable row level security;
alter table public.maintenance_schedules enable row level security;
alter table public.tires enable row level security;
alter table public.settings enable row level security;

create policy owner_only on public.vehicles for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy owner_only on public.maintenance_records for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy owner_only on public.maintenance_schedules for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy owner_only on public.tires for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy owner_only on public.settings for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

revoke all on public.vehicles, public.maintenance_records, public.maintenance_schedules, public.tires, public.settings from anon;
grant select, insert, update, delete on public.vehicles, public.maintenance_records, public.maintenance_schedules, public.tires, public.settings to authenticated;
grant usage, select on sequence public.vehicles_id_seq, public.maintenance_records_id_seq, public.maintenance_schedules_id_seq, public.tires_id_seq to authenticated;

-- Completing twice does not duplicate the optional expense record. The row lock
-- and transaction also protect concurrent requests and partial network failures.
create function public.complete_maintenance(schedule_id bigint, service_record jsonb default null)
returns void language plpgsql security invoker set search_path = '' as $$
declare
  scheduled public.maintenance_schedules;
begin
  if auth.uid() is null then raise exception 'Sign in first'; end if;
  select * into scheduled from public.maintenance_schedules
    where id = schedule_id and user_id = auth.uid() for update;
  if not found then raise exception 'Schedule no longer exists'; end if;
  if service_record is not null and (service_record->>'vehicle_id')::bigint is distinct from scheduled.vehicle_id then
    raise exception 'The record must belong to the scheduled vehicle';
  end if;
  if scheduled.status = 'completed' then return; end if;
  update public.maintenance_schedules set status = 'completed' where id = schedule_id and user_id = auth.uid();
  if service_record is not null then
    insert into public.maintenance_records (user_id, vehicle_id, maintenance_type, service_date, odometer, cost, service_provider, notes)
    values (auth.uid(), scheduled.vehicle_id, service_record->>'maintenance_type',
      (service_record->>'service_date')::date, (service_record->>'odometer')::double precision,
      (service_record->>'cost')::double precision, coalesce(service_record->>'service_provider', ''), coalesce(service_record->>'notes', ''));
  end if;
end;
$$;

-- Derive conversion from stored units, never from a possibly stale client value.
create function public.change_distance_unit(new_unit text)
returns void language plpgsql security invoker set search_path = '' as $$
begin
  if auth.uid() is null then raise exception 'Sign in first'; end if;
  if new_unit is null or new_unit not in ('km', 'mi') then raise exception 'Invalid unit'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(auth.uid()::text));
  perform id from public.vehicles where user_id = auth.uid() for update;
  update public.maintenance_records r set odometer = r.odometer *
    case when v.odometer_unit = new_unit then 1 when new_unit = 'mi' then 1 / 1.609344 else 1.609344 end
    from public.vehicles v where r.vehicle_id = v.id and r.user_id = auth.uid() and v.user_id = auth.uid();
  update public.maintenance_schedules s set due_odometer = s.due_odometer *
    case when v.odometer_unit = new_unit then 1 when new_unit = 'mi' then 1 / 1.609344 else 1.609344 end
    from public.vehicles v where s.vehicle_id = v.id and s.user_id = auth.uid() and v.user_id = auth.uid();
  update public.vehicles set current_odometer = current_odometer *
    case when odometer_unit = new_unit then 1 when new_unit = 'mi' then 1 / 1.609344 else 1.609344 end,
    odometer_unit = new_unit where user_id = auth.uid();
  insert into public.settings(user_id, key, value) values(auth.uid(), 'unit', new_unit)
    on conflict(user_id, key) do update set value = excluded.value;
end;
$$;

-- Import only into an empty garage; remap local IDs instead of reusing them.
-- Original local rows are never deleted. Import markers make retries idempotent.
create function public.import_local_garage(payload jsonb, import_id text)
returns integer language plpgsql security invoker set search_path = '' as $$
declare
  v jsonb;
  child jsonb;
  new_id bigint;
  mapping jsonb := '{}'::jsonb;
  preferences jsonb := coalesce(payload->'settings', '{}'::jsonb);
  count_imported integer := 0;
  preferred text;
begin
  if auth.uid() is null then raise exception 'Sign in first'; end if;
  if import_id is null or length(import_id) < 1 then raise exception 'Missing import ID'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(auth.uid()::text));
  if exists(select 1 from public.settings where user_id = auth.uid() and key = 'import:' || import_id) then return 0; end if;
  if exists(select 1 from public.vehicles where user_id = auth.uid()) then
    raise exception 'Import requires an empty cloud garage. Your local records are unchanged.';
  end if;
  if jsonb_typeof(payload->'vehicles') is distinct from 'array' or jsonb_array_length(payload->'vehicles') = 0 then
    raise exception 'No vehicles to import';
  end if;
  for v in select value from jsonb_array_elements(payload->'vehicles') loop
    insert into public.vehicles(user_id, nickname, make, model, year, plate_number, current_odometer, odometer_unit, notes)
      values(auth.uid(), v->>'nickname', v->>'make', v->>'model', (v->>'year')::integer,
        v->>'plate_number', (v->>'current_odometer')::double precision, v->>'odometer_unit', coalesce(v->>'notes', ''))
      returning id into new_id;
    mapping := mapping || jsonb_build_object(v->>'id', new_id);
    insert into public.settings(user_id, key, value)
      values(auth.uid(), 'interval_' || new_id, coalesce(preferences->>('interval_' || (v->>'id')), preferences->>'interval', '10000'))
      on conflict(user_id, key) do update set value = excluded.value;
    count_imported := count_imported + 1;
  end loop;
  for child in select value from jsonb_array_elements(coalesce(payload->'records', '[]'::jsonb)) loop
    insert into public.maintenance_records(user_id, vehicle_id, maintenance_type, service_date, odometer, cost, service_provider, notes)
      values(auth.uid(), (mapping->>(child->>'vehicle_id'))::bigint, child->>'maintenance_type', (child->>'service_date')::date,
        (child->>'odometer')::double precision, (child->>'cost')::double precision, coalesce(child->>'service_provider', ''), coalesce(child->>'notes', ''));
  end loop;
  for child in select value from jsonb_array_elements(coalesce(payload->'schedules', '[]'::jsonb)) loop
    insert into public.maintenance_schedules(user_id, vehicle_id, maintenance_type, due_date, due_odometer, notes, reminder_enabled, status)
      values(auth.uid(), (mapping->>(child->>'vehicle_id'))::bigint, child->>'maintenance_type', (child->>'due_date')::date,
        (child->>'due_odometer')::double precision, coalesce(child->>'notes', ''), (child->>'reminder_enabled')::integer, child->>'status');
  end loop;
  for child in select value from jsonb_array_elements(coalesce(payload->'tires', '[]'::jsonb)) loop
    insert into public.tires(user_id, vehicle_id, position, brand, manufactured_on, replacement_years, notes)
      values(auth.uid(), (mapping->>(child->>'vehicle_id'))::bigint, child->>'position', coalesce(child->>'brand', ''),
        (child->>'manufactured_on')::date, (child->>'replacement_years')::integer, coalesce(child->>'notes', ''));
  end loop;
  preferred := coalesce(mapping->>(preferences->>'selected_vehicle'), mapping->>(payload->'vehicles'->0->>'id'));
  insert into public.settings(user_id, key, value) values
    (auth.uid(), 'selected_vehicle', preferred),
    (auth.uid(), 'unit', coalesce(preferences->>'unit', payload->'vehicles'->0->>'odometer_unit', 'km')),
    (auth.uid(), 'notifications', 'false'),
    (auth.uid(), 'import:' || import_id, count_imported::text)
    on conflict(user_id, key) do update set value = excluded.value;
  return count_imported;
end;
$$;

revoke all on function public.complete_maintenance(bigint, jsonb) from public, anon;
revoke all on function public.change_distance_unit(text) from public, anon;
revoke all on function public.import_local_garage(jsonb, text) from public, anon;
grant execute on function public.complete_maintenance(bigint, jsonb) to authenticated;
grant execute on function public.change_distance_unit(text) to authenticated;
grant execute on function public.import_local_garage(jsonb, text) to authenticated;
commit;
